### ISSUE TITLE
Different KID in JWK uri and JWT token causing Exception

### ISSUE THREAD

**Issue by saravana2906** [jzheaux/spring-security-oauth2-resource-server#61]
Using Spring Boot OAuth Resource Server starter project, Version - 2.4.4.
I'm receiving the below exception, I couldn't find much problem in code as it worked fine in our preprod env 
 but not working in prod environment <br>
**Observation so far,** <br>
I have checked , and want to confirm **if kid received from jwk uri and kid received from token is different , then  Is it possible for this exception ?** Note , kid is same for token and jwk uri in pre-prod env but different in prod environment<br>
**from jwk uri** - <br>
[![enter image description here][1]][1] <br>
**from jwt header** - <br>
[![enter image description here][2]][2]<br>
Looked into this [code][3] , for key id checking snippet , line no- 253 .. but i couldn't understand further into it.

    com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
    	at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:384) ~[nimbus-jose-jwt-8.20.2.jar:8.20.2]
    	at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:330) ~[nimbus-jose-jwt-8.20.2.jar:8.20.2]
    	at org.springframework.security.oauth2.jwt.NimbusJwtDecoder.createJwt(NimbusJwtDecoder.java:153) ~[spring-security-oauth2-jose-5.4.5.jar:5.4.5]

  [1]: https://i.stack.imgur.com/DIiJS.png
  [2]: https://i.stack.imgur.com/ZULij.png
  [3]: https://javadoc.io/doc/com.nimbusds/nimbus-jose-jwt/4.2/src-html/com/nimbusds/jwt/proc/DefaultJWTProcessor.html

**Comment by jzheaux** [comment]
Your analysis appears correct. If the `kid` values do not match, then that key will not be used for verification. If that is the only key, then this is the exception that will be thrown.
